### ISSUE TITLE
ProjectRed's Liquid Redstone breaks Signalum's smeltery recipe.

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#10]
Issue:
With ProjectRed, this becomes Liquid Redstone, which breaks the Thermal Signalum recipe in the smeltery.

Expected:
Without ProjectRed in the picture, a smeltery will melt redstone into destabilized redstone.

Suggested fix:
Force ProjectRed to either use destabilized redstone, or ore dictionary Liquid Redstone.

**Comment by Almagnus1** [comment]
Workaround is to tweak Project Red to disable TConstruct integration.

Assuming that the world gen changes don't completely screw up the Iguana's progression, the work around may be sufficient, as the real solution is to going to take time to figure out, and may not be possible.

**Comment by Entity325** [comment]
I'm in favor of forcing ProjectRed to use destabilized redstone, how difficult is that?

Aside: I'm pretty sure creating destabilized redstone in the Smeltery requires Blazing Pyrotheum as fuel.

**Comment by Almagnus1** [comment]
You'd need to create recipes for the smeltery - which is not something I've done before.  Unlike ender IO, this may be quite complicated.

**Comment by Almagnus1** [comment]
Just did some experimenting with the smeltery, and you do need blazing pyrotheum as a fuel source.  If you can make pyrotheum, you can use the smeltery to melt it, using lava as the fuel source.

Also, redstone does require pyrotheum as the fuel to smelt.

As far as the other thermal stuff goes, you can make enderium and hardened glass with only lava as the fuel, because it also allows you to make end stone.

Using the above, you can make a resonant energy cell and tesseract using just the smeltery.  Granted, that's a really slow process compared to what Thermal Expansion can do once upgrades are used

Balance wise, that seems fine to me as you're trading speed for having to find this stuff initially (keep in mind that shiny ore/platinum is about as rare as iridium is).

**Comment by Almagnus1** [comment]
Closing, as this is something I'm OK with not having the smeltery do.
