### ISSUE TITLE
EnderIO Alloy Smelter can't make Tinker's Alloys

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#11]
Issue:
The EnderIO Alloy Smelter should be able to make Aluminum Brass and Alumite

Actual:
The EnderIO Alloy Smelter will not accept Aluminum as a valid material when in Furnace Mode

Expected:
The EnderIO Alloy Smelter should have recipes for Aluminum Brass and Alumite considering that it can be used as an alternate path to make enderium.

**Comment by Entity325** [comment]
Is this a side-effect of work done for #9?

**Comment by Almagnus1** [comment]
No, the Alloy Smelter will not accept Aluminum as a material, likely because it doesn't know what those definitions are.

Considering where they are used in progression, it's a polish thing really.

**Comment by Entity325** [comment]
Aluminum Brass mix is a 4:1 aluminum to copper ratio, and I'm personally OK with restricting it and similar alloys to the Smeltery.

Maybe make it a stretch goal. Lowest priority.

**Comment by Almagnus1** [comment]
Yeah, it's a definite low pri thing.  Most of us probably won't know it's missing.

**Comment by Almagnus1** [comment]
This is doable with a tweak to the EnderIO configs.

A related issue may be solved, but needs ModTweaker: https://github.com/Almagnus1/IaconClient/issues/17

**Comment by Almagnus1** [comment]
Resolved with: 
https://github.com/Almagnus1/IaconConfig/commit/a0ee60380a9501f3e42b4157a27c3d2098fc3080
