### ISSUE TITLE
Minetweaker Tweaking

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#15]
Dug a bit deeper into one of the mdos in the modpack, and:

http://minetweaker3.powerofbytes.com/about.html

That's the tools needed to redefine any of the recipes in the pack, or possibly create new ones.

**Comment by Entity325** [comment]
That sounds unbelievably useful.

**Comment by Almagnus1** [comment]
Yep, MineTweaker RecipeMaker makes generating the script to rework a recipe cake.

Just get all the components in creative, do a /mtrm to open it up, and generate the recipe.  Then it's a matter of taking the recipe and cleaning it up so it looks something like the following.

So what needs to be reworked?

```
// why we change it
val target = <mod:part>;
val part1 = <mod:part>;
val part2 = <ore:part>;
val part3 = <ore:part>;

recipes.remove(target);
recipes.addShaped(target, [[part1, null, part2], [null, part3, part1], [part1, part2, part3]]);
```
