### ISSUE TITLE
B.0.1 Changelist

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#16]
Gathering up the changes for the next release, likely a minor one as it's just config tweaks (not expecting forge to have a new stable 1.7.10 as they are likely moving on to 1.8+).

So far:
- Added Aluminum Brass, Alumite, and Manyullyn recipes to EnderIO's Alloy Smelter
- Optimized modpack infrastructure files.

**Comment by Almagnus1** [comment]
A few more:
- Adjusted Morpheus sleep vote percentage to 40%, down from 50%.
- Reduced Khndrel Keght spawn percentage to 50%, down from 65%
- Fixed Thermal Foundation Lead, Silver, and Tin world gen bug.
- Enabled in Tinkers Construct Tin Spawn
- Removed Autosmelt and Silktouch from the Iguana Tweaks random tool enchant pool.  They must be added on manually with one of your upgrades.

**Comment by Entity325** [comment]
I would take the Khndrel Keght spawn rate all the way down to 35-40%. Ironically, this would actually make them more annoying, but it should also make them less of a hassle.

If TC tin is going to spawn, I would disable TE tin, as it looks enough like silver to be confusing. My typical hint that I'm mining tin instead of silver is that there's no lead in the spawn.

**Comment by Almagnus1** [comment]
From what I have heard of TConstruct for 1.8, it's going to completely drop it's world gen - so the goal is to have Thermal Foundation do the world gen exclusively.

**Comment by Almagnus1** [comment]
A couple more:
- Fixed the Chisel Iron Chisel recipe to not conflict with the Pam's Harvestcraft Saucepan.
- Adjusted the Buildcraft quarry recipe.
- Disabling railcraft metal world generation.
- Enabled Ender IO jetpacks in Simply Jetpacks.

**Comment by Almagnus1** [comment]
- Added lead only pass to Thermal Foundation world generation

**Comment by Almagnus1** [comment]
On a side note, the scripts should be pushed from the server to the client, so as long as no one cares about solo play with the mod pack, everything should work if the servers at B.0.1 and the clients aren't.

I'm not sure about the configs, as there may be some odd behavior introduced by the mismatch.

**Comment by Almagnus1** [comment]
- Long Fall Boots Balance Pass
- Fixed an issue with the Mapwriter mod (added by Opis) where it's minimap would start open.  It should now start closed.

**Comment by Almagnus1** [comment]
- Modular Powersuits recipe cleanup
- Fixed an issue with RC steel

**Comment by Almagnus1** [comment]
Client and config now have release branches.

**Comment by Almagnus1** [comment]
Client version uploaded to Curse, and project has made the request to have the experimental tag removed.

**Comment by Almagnus1** [comment]
Server updated, and zip created.

B.0.0 clients should be expected to connect to the B.0.1 server without issue.

**Comment by Almagnus1** [comment]
From testing, found that B.0.1 clients can connect to the B.0.0 server.

Production server is currently in a halfway state between B.0.0 and B.0.1, and will likely be that way until the clients have had a chance to update to B.0.1.
