### ISSUE TITLE
Can't Craft Iron Chisel

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#18]
Issue:
When trying to craft the iron chisel, I get cookware from Pam's Harvestcraft instead of the iron chisel.

This looks like an issue with shapeless crafting and Pam's Harvestcraft.

Expected:
Should be able to craft both items

Workaround:
Use the diamond chisel

**Comment by Entity325** [comment]
Oh is THAT why you were asking about pans last night?

**Comment by Almagnus1** [comment]
Resolved by changing the Chisel Chisel script to:
(null) (iron ingot)
(stick) (null)

https://github.com/Almagnus1/IaconClient/commit/6c462c155e3a675a04ed177d42e2cffbbb867605
