### ISSUE TITLE
Platinum Ore is too common

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#19]
Issue:
Platinum Ore seems to be spawning more frequently than anticipated

Note:
Platinum Ore spawns with nickel, and nickel had it's weight changed from 16 to 10 prior to beta.  This value may be too low, and it's causing platinum to be more common than usual.

This may cause issue as platinum may be common enough to be a viable armor material, which is not intended.

Will continue to monitor, and see if this is just luck, or if this is an actual issue.

**Comment by Entity325** [comment]
Platinum and nickel may have been too rare at 16, they're definitely too common at 10. Suggest trying 14 at next world regen.

**Comment by Almagnus1** [comment]
https://github.com/Almagnus1/IaconConfig/commit/93ecc418fc977a15196e13cf84ceea2e27d51b3f should hopefully resolve this.  Will leave this open and continue to monitor, as there's no easy way to test this short of a world reset.

**Comment by Almagnus1** [comment]
Closing, as https://github.com/Almagnus1/IaconClient/issues/14 is tied to this issue.
