### ISSUE TITLE
Longfall Boots Balance Pass

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#25]
Longfall Boots need to either take damage (as normal armor would), or have reduced armor.

As they are now, they are one of the best boots in the game.

**Comment by Almagnus1** [comment]
No option in the config file to alter the boots, need to do this from another mod.

**Comment by Almagnus1** [comment]
After a bit of research into the possibility of tweaking armor, the solution is either another mod, or adjust the recipe to make the boot a bit harder to complete.

I'm thinking of going with the latter, and using something like this recipe per boot (you need two boots for a set):
(manyullyn ingot) (obsidian) (platinum ingot)
(iron ingot) (diamond) (iron ingot)
(iron ingot) (diamond) (iron ingot)

**Comment by Entity325** [comment]
I think the manyullyn may be a bit overkill as that's rare even in the post-endgame stage(farming the End), at which point there are better options available (wings which allow true Creative-style flight). If we assume the target stage for long-fall boots is Late-game (post-Nether, pre-End), then I wouldn't go any higher than cobalt.

Alternative suggestion:
Cobalt ingot, diamond, Cobalt ingot
Shiny ingot, obsidian, Shiny ingot
Shiny ingot, obsidian, Shiny ingot
(per-boot)

This is slightly more expensive as far as Cobalt is concerned, but Cobalt is the easier of the two Nether ores to acquire

(It's worth noting that the default recipe puts the boots in late-midgame: ready to enter the Nether)

**Comment by Almagnus1** [comment]
Going with a slightly different recipe: 

https://github.com/Almagnus1/IaconClient/commit/b40a4c4537d6ec24b4682d815e3b1b82e5b407e8
