### ISSUE TITLE
Lead Ore Standard generation

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#26]
Lead ore is a bit too rare, especially considering how much of a demand simply jetpacks puts on lead.

There should be a standard generation of lead only added to the Thermal Foundation generation from Y level 30-40 down to bedrock.

**Comment by Entity325** [comment]
I assume this would also eliminate the lead ore that spawns with silver. I think lead needs to be more common, but not too much so.

**Comment by Almagnus1** [comment]
Actually, no.

It would be an additional ore generation pass that's lead only, as I would leave the lead/silver spawns alone as silver is good enough for the moment.

**Comment by Entity325** [comment]
in that case, I would have the new pass stop at the same level that the lead/silver spawns start.

**Comment by Almagnus1** [comment]
Should be solved with:
https://github.com/Almagnus1/IaconConfig/commit/b0ceb72eab5394308eb5490873b0b00ce409eb6b

Closing, as this issue is tied to https://github.com/Almagnus1/IaconClient/issues/14
