### ISSUE TITLE
Nerf the BC quarry recipe

### ISSUE THREAD

**Issue by Entity325** [Almagnus1/IaconClient#27]
BC Quarry recipe was made more expensive to discourage world-eaters and lagmachines, but now it currently requires 8 Ender pearls, which puts it into post-endgame. (Ender pearls are not readily available until the Ender can be farmed)

Suggested new recipe:
Diamond Gear, Reception Coil, Diamond Gear
Signalum Gear, Enderium Gear, Signalum Gear
Shiny Gear, Shiny Pick, Shiny Gear

This reduces the Ender pearl cost from 8 to a more reasonable 4 and reintroduces diamonds into the requirement recipe.

Balance notes: expect average players to encounter between 6 and 8 Ender pearls naturally before beginning the Endgame phase, this allows them to use the remaining 2-4 for something else.

**Comment by Almagnus1** [comment]
Resolved in https://github.com/Almagnus1/IaconClient/commit/6c462c155e3a675a04ed177d42e2cffbbb867605

**Comment by Entity325** [comment]
You sure about that? The change points to an update to the iron Chisel recipe.

**Comment by Almagnus1** [comment]
Should be https://github.com/Almagnus1/IaconClient/commit/caf10d883f02d282efd4172cf7eedc86d0885072 >.>

**Comment by Entity325** [comment]
that's more like it.
