### ISSUE TITLE
Mod request: Agricraft

### ISSUE THREAD

**Issue by Entity325** [Almagnus1/IaconClient#28]
http://mods.curse.com/mc-mods/minecraft/225635-agricraft

mod intended to improve upon IC2 crop system by adding some sense to it. Crop mutations can be nerfed via config file.

My interest is chiefly in the irrigation system which provides growth speed boosts to almost all plants instead of just wheat, like OpenBlocks sprinklers do.

**Comment by Almagnus1** [comment]
I'll take a look into this mod, but you should really look into the growth accelerations of Botania and Thaumcraft, as there are devices in there that should do the same thing.

**Comment by Entity325** [comment]
Haven't checked Thaumcraft. Nydilia and I checked the Botania flowers and they only work for wheat.
