### ISSUE TITLE
Aroma Mods for inclusion?

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#3]
From the Server side, Aroma Backup is a must have (and will get added eventually), but another mod raised an eyebrow, specifically [Aroma1997s Dimensional World (Mining World Mod)](http://minecraft.curseforge.com/projects/aroma1997s-dimensional-world).

This would be a nice addition to prevent the destruction of the Overworld, Nether, End, The Dark, and Twilight Forest.

**Comment by Entity325** [comment]
Dimensional World: reject. Mystcraft already does that and better.

**Comment by Almagnus1** [comment]
Yeah, that's the same conclusion I came to too.  Closing issue.
