### ISSUE TITLE
Enable Ender IO flavor equipment in Simply Jetpacks mod

### ISSUE THREAD

**Issue by Entity325** [Almagnus1/IaconClient#30]
The TC-flavor equipment (leadstone/hardened/reinforced/resonant jetpacks and flux-infused jetplate) are currently enabled, but some people on the server (Almagnus1) like Ender IO.

The EIO-flavor equipment(conductive iron/electrical steel/energetic/vibrant jetpacks and dark solarium jetplate) will add a different tech path which may be more suitable for certain builds or resource environments, and will also provide an alternate aesthetic choice so everyone doesn't end up flying around in golden power armor.

**Comment by Almagnus1** [comment]
Enabled with https://github.com/Almagnus1/IaconConfig/commit/2fb49db38538b9c7130cda18d76c50d0183b4954
