### ISSUE TITLE
Steel armor needs smeltery recipes

### ISSUE THREAD

**Issue by Entity325** [Almagnus1/IaconClient#34]
Namely, the ability to melt the parts down. Chain has it, steel doesn't.

Helm -> 720mb
chest -> 1152mb
leggings -> 1008mb
boots -> 576mb

(144mb = 1 ingot, values based on crafting recipes)

**Comment by Almagnus1** [comment]
This is going to be a B.1.0 change as the solution is:
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support
