### ISSUE TITLE
Disable Morph

### ISSUE THREAD

**Issue by Entity325** [Almagnus1/IaconClient#4]
Morph can be fun, but it also allows high-speed flight(bat form) and swimming(squid form) early-game, significantly reduces risks in the Nether at little cost (non item-dependent flight mode, again, as well as immunity to magma from fire bats or any Vanilla Nether mob).

**Comment by Almagnus1** [comment]
Yeah, I can see the logic here, and removal also makes the flight mechanics feel like an achievement once you get them.

Need to think on this one more, as personally I'm right in the middle, and not on one side or the other.

**Comment by Almagnus1** [comment]
Actually, looking at https://github.com/Almagnus1/IaconClient/issues/7 , we might be better off swapping one mod for another, as we lost the early game flight when IC2 was dropped.

**Comment by Almagnus1** [comment]
Morph is getting swapped out for Simply Jetpacks.  Change will be committed shortly.
