### ISSUE TITLE
Bedrock isn't flat

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#5]
This is a "nice to have", and not a blocking issue.

The bedrock layer should be one block tall, and completely flat - instead of using the vanilla noise generation.

**Comment by Entity325** [comment]
I believe this is a Vanilla worldgen flag you can set in one of the .properties files. I do remember messing around with Nydilia in a test world where the bedrock was flat.

We played Spleef on it.

**Comment by Almagnus1** [comment]
Found the setting, and fixed the gen.
