### ISSUE TITLE
Adjust Starting Kit

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#6]
Starting kit really needs to have more food with it, as the server will be running on hard mode, and one apple isn't enough to get players going initially.

**Comment by Entity325** [comment]
Maybe not if you do it wrong.

**Comment by Almagnus1** [comment]
In the big scheme of things, I don't think giving someone like 5 loaves of bread and an apple is going to be game breaking =P

**Comment by Entity325** [comment]
I was actually discussing with Coshne, I think 5 apples in the starting kit wouldn't be inappropriate.

**Comment by Almagnus1** [comment]
Yeah, trick is diving into the configs and figuring out how the user is getting two books and an apple on spawn.
