### ISSUE TITLE
Mod request: Simply Jetpacks

### ISSUE THREAD

**Issue by Entity325** [Almagnus1/IaconClient#7]
Website: http://mods.curse.com/mc-mods/minecraft/simply-jetpacks

Early and mid-game jetpack-style flight(in comparison to the Creative-style flight that wings provide post-endgame), jetpacks can be upgraded to fairly high-end armor late-game.

**Comment by Almagnus1** [comment]
I looked into this, and it also feels like it needs Redstone Arsenal, which is also getting added.
