### ISSUE TITLE
Improved main menu

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#8]
The main menu is... well... not very interesting.

Perhaps it needs something more awesome?

PS: The JSON must be ASCII encoded or you will crash.

**Comment by Entity325** [comment]
Main menu doesn't need to be awesome. Ideally nobody will spend any real amount of time there.

**Comment by Almagnus1** [comment]
Eh, it's more that it just looks so.... bleh.... compared to other modpacks I've been looking at.

It's not a critical thing by any stretch of the mind, but it is something that needs to be less vanilla than it currently is.
